Homework 1 , tasks BinarySearch, SelectionSort.
glockbender/programyata-tasks pull request #10
Opened 2021-04-05 19:54 UTC by Nikita14141996

2021-04-05 21:56 UTC, Toreador23 approved these changes
Всё увидел, не вчитывался, потому что моё ещё не готово. Выглядит так, будто соблюдены все правила чистого кода:) Остальное предоставим Илье:)

2021-04-05 22:39 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/homework/binarysearch/BinarySearch.java
> +    public static void Binary(int[] array, int item, int first, int last) {
Методы стоит называть с маленькой буквы

2021-04-05 22:39 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/homework/selectionsort/SelectionSort.java
> +            for (int j = min; j < array.length; j++) {
Почему бы не начинать итерироваться по j сразу с min + 1 ?

2021-04-05 22:39 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/homework/binarysearch/BinarySearch.java
> +            } else if (array[mid] == item) {
в данном случае достаточно просто оставить else, т.к. все условия кроме равенства уже выполнены выше

2021-04-05 22:40 UTC, glockbender requested changes
Все ок, красавчик. Как исправишь замечания - пингани, я заапрувлю

2021-04-06 08:36 UTC, glockbender approved these changes

2021-04-06 08:39 UTC, merged