Home work almost done, next step is two varies of Sherlock + tasks fr…
glockbender/programyata-tasks pull request #19
Opened 2021-04-20 13:14 UTC by Toreador23

…om HR

2021-04-20 14:39 UTC, glockbender requested changes

2021-04-20 14:39 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson3/Hourglass.java
> +        int sum1 = 0;
sum1 стоит быть внутри for, т.к. снаружи эта переменная не используется. Плюс, стоит назвать переменную более осмысленно. Например innerSum

2021-04-20 14:39 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson3/Hourglass.java
> +        int sum2 = Integer.MIN_VALUE;
В задаче есть ограничение, что мин сумма не более -63. Судя по коду, данная переменная является результатом выполнения. Можно назвать ее например resultSum

2021-04-22 12:59 UTC, Nikita14141996 approved these changes

2021-04-22 18:03 UTC, Toreador23 commented on first-ruslan/src/main/java/com/ruslan/lesson3/Hourglass.java
> +        int sum1 = 0;
Поправил в последнем коммите!

2021-04-22 18:03 UTC, Toreador23 commented on first-ruslan/src/main/java/com/ruslan/lesson3/Hourglass.java
> +        int sum2 = Integer.MIN_VALUE;
Поправил в последнем коммите!

2021-04-22 20:37 UTC, glockbender approved these changes

2021-04-22 20:39 UTC, merged