lesson3.5,homework without Sherlock.
glockbender/programyata-tasks pull request #20
Opened 2021-04-22 12:45 UTC by Nikita14141996

2021-04-22 19:17 UTC, Toreador23 approved these changes
Неплохой способ решения песочных часов!

2021-04-22 20:41 UTC, glockbender requested changes
Все ок. Молодец. Набирай обороты с задачами на хакерранке. Как поправишь замечания - маякни

2021-04-22 20:41 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson3/homework2/JumpingClouds.java
> +/*int count = 0;
Если код не нужен - удали

2021-04-22 20:41 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson3/homework3/HackerRankDateAndTime.java
> +        return ""+ date.getDayOfWeek();
date.getDayOfWeek().toString();

2021-04-25 08:26 UTC, glockbender approved these changes

2021-04-25 08:26 UTC, merged