Practical part of homework 3.6 done
glockbender/programyata-tasks pull request #21
Opened 2021-04-24 19:44 UTC by Toreador23

2021-04-25 07:20 UTC, Nikita14141996 approved these changes

2021-04-25 08:43 UTC, glockbender requested changes

2021-04-25 08:43 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/lesson3_6/BubbleSortTest.java
> +    public void BubbleSort_should_throw_Exception_when_array_is_null() {
Раз ты изменил поведение, измени и название тест кейса

2021-04-25 08:43 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/lesson3_6/BubbleSortTest.java
> +        int[] expected4 = new int[1000];
вынеси создание массива произвольной длины в отельный приватный метод

2021-04-25 08:43 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/lesson3_6/BubbleSortTest.java
> +        for (int j = 0; j < 1000; j++) {
Рандомизацию произвольного массива можно вынести в приватный метод

2021-04-25 08:43 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/lesson3_6/SelectionSortTest.java
> +    public void SelectionSort_should_throw_Exception_when_array_is_null() {
Раз ты изменил поведение, измени и название тест кейса

2021-04-26 12:15 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/lesson3_6/BinarySearchTest.java
> +public class BinarySearchTest {
Добавить тест на проверку корректных low и high. Т.к. не оч понятно, для массива из 100 эл. значения от 0..99 или 1..100

2021-04-28 19:35 UTC, glockbender approved these changes

2021-04-28 19:35 UTC, merged