lesson3.6, tasks :BubbleSortTest,SelectionSortTest,BinarySearchTest
glockbender/programyata-tasks pull request #22
Opened 2021-04-25 07:27 UTC by Nikita14141996

2021-04-25 08:36 UTC, glockbender requested changes

2021-04-25 08:36 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/BinarySearchTest.java
> +    }
Добавь тест, когда ты ищешь значение, которого нет в массиве. А то "Вася" что-то напортачит в методе, и он начнет находить несуществующие элементы

2021-04-28 19:35 UTC, glockbender approved these changes

2021-04-28 19:38 UTC, Toreador23 approved these changes
по названию границ: считаю, если первая задана from, вторая лучше чтоб была to. Букв меньше, смысловой перевод соблюдён (от, до). Для границы Last первая граница должна быть First. (Илья просил докапываться до кода). В остальном порядок, продолжай в том же духе!

2021-04-28 19:48 UTC, merged