Nikita/lesson4.0.1 test creation, error correction
glockbender/programyata-tasks pull request #23
Opened 2021-04-29 12:26 UTC by Nikita14141996

2021-04-29 13:34 UTC, glockbender requested changes

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson1/BubbleSort.java
> +    private static void swap(int[] array, int from, int to) {
Метод, используемый только в одном месте и всего из 3 строк не имеет смысла

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson1/homework/binarysearch/BinarySearch.java
> +            return 0;
-1

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson1/homework/binarysearch/BinarySearch.java
> +        return -1;
У тебя всегда возвращается -1. Нужно исправить

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson2/SimpleArraySum.java
> +        if (ar == null) {
ar == null || ar.length == 0

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/main/java/com/nikita/lesson3/Rle.java
> +        // System.out.println(rle.zip(stroka));
Если код не используется - убери

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/BinarySearchTest.java
> +        Assertions.assertEquals(item, 55);
вместо 55 подставить binarySearch.binary(array, item)

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/BinarySearchTest.java
> +    public void BinarySearch_works_correctly_without_the_needed_element() {
Некорректное название метода

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/BubbleSorT.java
> +        int [] arraySort=ArrayTestUtils.copyAndShuffle(arrayBubleSort);
Arrays.copy(arrayBubleSort)

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/SelectionSortTest.java
> +        int [] sortArray= ArrayTestUtils.copyAndShuffle(selArray);
Arrays.copy(arrayBubleSort)

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/AlternatingCharactersTest.java
> +        altChar.alternatingCharacters(s);
Assertions.assertEquals(0, AlternatingCharacters.alternatingCharacters(s)); Метод возвращает число. Нужно проврять именно результат работы метода

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/AlternatingCharactersTest.java
> +        altChar.alternatingCharacters(s);
Assertions.assertEquals(0, AlternatingCharacters.alternatingCharacters(s));

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/AlternatingCharactersTest.java
> +    AlternatingCharacters altChar= new AlternatingCharacters();
У тебя статический метод. Не нужно создавать экземпляр класса для него

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/FactorialSumTest.java
> +    public void FactorialSum_works_correctly(){
FactorialSum.factorialsum(i); Это статический метод

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/FactorialSumTest.java
> +        int result = new FactorialSum().factorialsum(i);
FactorialSum.factorialsum(i);

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/RleTest.java
> +
Assertions.assertEquals("", rleLine);

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/RleTest.java
> +
Assertions.assertEquals("", newLine);

2021-04-29 13:34 UTC, glockbender commented on first-nikita/src/test/java/com/nikita/lesson3_6/lesson4/RleTest.java
> +
String zipped = rle.zip(s);
        String unzipped = rle.unzip(zipped);

        Assertions.assertEquals(s, unzipped);

2021-05-01 17:54 UTC, glockbender approved these changes

2021-05-02 08:23 UTC, Toreador23 approved these changes

2021-05-02 08:33 UTC, merged