techDebt closed particularly, created and used string generator.
glockbender/programyata-tasks pull request #24
Opened 2021-04-29 13:10 UTC by Toreador23

2021-04-29 13:55 UTC, glockbender requested changes

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson2/SumOfArrayElements.java
> +        if(ar == null) {
if(ar == null || ar.length == 0)

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson2/homework/rle/AlternatingCharacters.java
> +        if (s==null) {
if (s==null || s.isEmpty()) {

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson2/homework/rle/Rle.java
> +        if (unzipped == null) {
if (unzipped == null || unzipped.isEmpty()) {

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson2/homework/rle/Rle.java
> +        if (zipped == null) {
if (unzipped == null || unzipped.isEmpty()) {

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/main/java/com/ruslan/lesson2/homework/rle/Rle.java
> +        }
Убрать

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/AlternatingCharactersTest.java
> +
Сделать проще

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/FactorialTest.java
> +        int expected_i = 1;
CamelCase

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/FactorialTest.java
> +            int result_i = Factorial.factorial(n);
CamelCase

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/FactorialTest.java
> +
new int[]{1,1,2,6,24...}
for (int i = 1; i<ar.len; i++) {
assertEq(ar[i], fact(i))
}

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/RleUnzipTest.java
> +        Assertions.assertEquals(null, input);
Лучше не возвращать null

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/RleZipTest.java
> +    @Test
Сделать один тестовый класс для всего RLE

2021-04-29 13:55 UTC, glockbender commented on first-ruslan/src/test/java/com/ruslan/homework/SumOfArrayElementsTest.java
> +        GenerateArrayUtils.sortedArray(0, 10);
Нет теста

2021-05-01 17:52 UTC, glockbender approved these changes

2021-05-02 08:31 UTC, Nikita14141996 approved these changes

2021-05-02 08:33 UTC, merged